version: "3"
services:
  db:
    container_name: "db"
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    container_name: "notes-backend"
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
volumes:
  pgdata:
networks:
  custom:
    driver: bridge
